/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.complexalpha;

import jp.complexalpha.poip.XlsxPoi;
import jp.complexalpha.fastx.XlsxFastx;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class App {

    public static void main(String[] args) throws IOException {

        String now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));
        String dir = args[0];

        System.out.println("POI EXCEL START");
        XlsxPoi.writeNewXlsx(dir + "/poi_" + now + ".xlsx");

        XlsxFastx.writeXlsx(dir + "/fastexel_" +  now + ".xlsx");
    }
}
