/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.complexalpha;

import jp.complexalpha.poip.XlsxPoi;
import jp.complexalpha.fastx.XlsxFastx;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

public class App {

    public static void main(String[] args) throws IOException {

        String fileTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));
        String dir = args[0];

        int testRows = 1000000;

        System.out.println("POI EXCEL START");
        long st_poi = ZonedDateTime.now().toEpochSecond();
        XlsxPoi.writeNewXlsx(dir + "/poi_" + fileTime + ".xlsx", testRows);
        System.out.print(ZonedDateTime.now().toEpochSecond() - st_poi);
        System.out.println(" ms");
        System.out.println("POI EXCEL END");

        System.out.println("FASTEXCEL EXCEL START");
        long st_fast = ZonedDateTime.now().toEpochSecond();
        XlsxFastx.writeNewXlsx(dir + "/fastexel_" +  fileTime + ".xlsx", testRows);
        System.out.print(ZonedDateTime.now().toEpochSecond() - st_fast);
        System.out.println(" ms");
        System.out.println("FASTEXCEL EXCEL END");
    }
}
